# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_playlist_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.IntegerField()),
                ('youtube_video_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('part', models.IntegerField()),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('playlists', models.ManyToManyField(blank=True, to='catv.Playlist')),
                ('tags', models.ManyToManyField(blank=True, to='catv.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
