# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
